apiVersion: app.m4d.ibm.com/v1alpha1
kind: M4DModule
metadata:
  name: arrow-flight-module
  labels:
    name: arrow-flight-module
    version: 0.0.1  # semantic version
spec:
  chart: ghcr.io/the-mesh-for-data/arrow-flight-module-chart:latest
  type: service
  flows:
    - read
  capabilities:
    credentials-managed-by: secret-provider
    api:
      protocol: m4d-arrow-flight
      dataformat: arrow
    supportedInterfaces:
    - flow: read
      source:
        protocol: s3
        dataformat: parquet
    - flow: read
      source:
        protocol: s3
        dataformat: csv
    actions:
      - id: redact-ID
        level: 2  # column
      - id: removed-ID
        level: 2  # column
