apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: arrow-flight-module
  labels:
    name: arrow-flight-module
    version: latest  # semantic version
spec:
  type: service
  chart:
    name: ghcr.io/fybrik/arrow-flight-module-chart:latest
    values:
      image.tag: latest
  capabilities:
    read:
      scope: workload
      api:
        endpoint:
          port: 80
          scheme: grpc
        protocol: fybrik-arrow-flight
        dataformat: arrow
      supportedInterfaces:
        - source:
            protocol: s3
            dataformat: parquet
        - source:
            protocol: s3
            dataformat: csv
      actions:
        - id: redact-ID
          level: 2  # column
        - id: removed-ID
          level: 2  # column
    - capability: write
      scope: workload
      api:
        endpoint:
          port: 80
          scheme: grpc
        protocol: fybrik-arrow-flight
        dataformat: arrow
      supportedInterfaces:
        - sink:
            protocol: s3
            dataformat: parquet
      actions:
        - id: redact-ID
          level: 2  # column
        - id: removed-ID
          level: 2  # column
