apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arrow-flight-module.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "arrow-flight-module.name" . }}
    helm.sh/chart: {{ include "arrow-flight-module.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arrow-flight-module.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arrow-flight-module.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- range $key, $val := .Values.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}    
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: {{ include "arrow-flight-module.fullname" . }}
      securityContext:
        {{- include "fybrik.processPodSecurityContext" (dict "context" . "podSecurityContext" .Values.podSecurityContext) | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- end }}
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          securityContext:
          {{- .Values.containerSecurityContext | toYaml | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - readOnly: true
              mountPath: /etc/conf
              name: config
      volumes:
        - name: config
          configMap:
            name: {{ include "arrow-flight-module.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
