name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  DOCKER_HOSTNAME: ghcr.io
  DOCKER_NAMESPACE: fybrik 
  DOCKER_USERNAME: ${{ github.actor }}
  # helm 3.7 chart tag must be semver
  HELM_TAG: 0.0.0
  DOCKER_TAG: latest

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: New tag
      if: ${{ (github.event_name != 'pull_request') && contains(github.ref, 'tags') }}
      run: |
        echo "DOCKER_TAG=${GITHUB_REF##*/v}" >> $GITHUB_ENV
        echo "HELM_TAG=${GITHUB_REF##*/v}" >> $GITHUB_ENV

    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        version: v3.7.0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install pipenv
    - name: Build docker image 
      run: make build
    - name: Docker push
      if: ${{ (github.event_name != 'pull_request') }}
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin "${{ env.DOCKER_HOSTNAME }}"
        make docker-push
    - run: docker images
    - name: Helm chart push
      if: ${{ (github.event_name != 'pull_request') }}
      run: |
        export HELM_EXPERIMENTAL_OCI=1 
        echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login -u "${{ github.actor }}" --password-stdin "${{ env.DOCKER_HOSTNAME }}" 
        make chart-push

